### ISSUE TITLE
Cannot publish in strapi 4.19.0

### ISSUE THREAD

**Issue by Alexnortung** [pluginpal/strapi-webtools#105]
### Describe the bug

When I try to publish a content type that has draft and publish enabled and webtools, I am now unable to publish it. I get an error saying that the `url_path` field must be unique

### Steps to reproduce the behavior

1. Create a content type with webtools and draft and publish enabled
2. create a pattern for it
3. Create an entry and save it (this should work)
4. try to publish it and see an error.

### Expected behavior

I expected that the entry would be published as normal

### System

- Node.js version: 18.18.2
- NPM version: 9.8.1
- Strapi version: 4.19.0
- Plugin version: 1.0.0-beta.5
- Database: sqlite
- Operating system: Linux

### Additional context

This might have something to do with the content releases that strapi added in this version
![billede](https://github.com/pluginpal/strapi-webtools/assets/1552267/6e00d610-9957-4f9c-9357-ce5c0196eb31)

https://github.com/strapi/strapi/releases/tag/v4.19.0

**Comment by boazpoolman** [comment]
This issue has been fixed, and released with [version 1.0.0-beta.6](https://github.com/pluginpal/strapi-webtools/releases/tag/%40pluginpal%2Fwebtools-core%401.0.0-beta.6).
