### ISSUE TITLE
"-0" at the end of the path

### ISSUE THREAD

**Issue by colpomatteo** [pluginpal/strapi-webtools#124]
### Describe the bug

Every time a content type is saved the plugin try to regenerate the path and it bounce between /[path]/ and /[path]/-0

### Steps to reproduce the behavior

1. Create an item of a content type with url_alias enabled and url_pattern like "/[title]/"
2. Add a title and save
3. You see the correct path "/[title]/"
4. Change some field (not the title) to trigger the ability to save again
5. Save
6. You se the wrong path "/[title]/-0"

### Expected behavior

Once the path is generated it updates only when the pattern fields are modified

### Screenshots

![immagine](https://github.com/pluginpal/strapi-webtools/assets/35310819/1e35c205-7ac6-4530-8776-ab2cbfc25aa1)

### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version: 20.11.0
- NPM version: 10.2.4
- Strapi version: 4.20.0
- Plugin version: 1.0.0-beta.7
- Database: Postgres
- Operating system: Linux

**Comment by colpomatteo** [comment]
I fixed it by editing `webtools-core/server/admin-api/services/url-alias.js` like so:
```javascript
/**
 * Finds a path from the original path that is unique
 */
const duplicateCheck = async (originalPath, ignoreId, ext = -1) => {
    const extension = ext >= 0 ? `-${ext}` : '';
    const newPath = originalPath + extension;
    const pathAlreadyExists = await (0, getPluginService_1.getPluginService)('urlAliasService').findByPath(newPath, ignoreId);
    if (!!pathAlreadyExists) { // 0 evaluates as true ¯\_(ツ)_/¯ so I added !!
        return duplicateCheck(originalPath, ignoreId, ext + 1);
    }
    return newPath;
};
```

**Comment by Alexnortung** [comment]
Interesting, this was an issue in `beta.6`, I am really not sure what could cause this issue. Are you certain that you are using `beta.7`?

**Comment by colpomatteo** [comment]
Yes, here are all my dependencies
![immagine](https://github.com/pluginpal/strapi-webtools/assets/35310819/8a49927a-eefd-442d-b6a4-b9c1c076eb1e)

**Comment by Alexnortung** [comment]
I am unable to reproduce this following the steps you have provided.

> I fixed it by editing built file `webtools-core/server/admin-api/services/url-alias.js` like so:
> 
> ```js
> /**
>  * Finds a path from the original path that is unique
>  */
> const duplicateCheck = async (originalPath, ignoreId, ext = -1) => {
>     const extension = ext >= 0 ? `-${ext}` : '';
>     const newPath = originalPath + extension;
>     const pathAlreadyExists = await (0, getPluginService_1.getPluginService)('urlAliasService').findByPath(newPath, ignoreId);
>     if (!!pathAlreadyExists) { // 0 evaluates as true ¯\_(ツ)_/¯ so I added !!
>         return duplicateCheck(originalPath, ignoreId, ext + 1);
>     }
>     return newPath;
> };
> ```

I don't see how this fixes the issue, `pathAlreadyExists` is a url alias entity or undefined, when does this ever become `'0'` @colpomatteo?

Have you taken any other steps for this to happen?

**Comment by colpomatteo** [comment]
Mmh, i reinstalled all the node_modules and the issue didn't showed up. I don't know why ¯\_(ツ)_/¯
Maybe it was using the beta.6 even if npm was showing beta.7
