### ISSUE TITLE
Break admin users panel

### ISSUE THREAD

**Issue by HighError** [pluginpal/strapi-webtools#137]
## Bug report

Installing the plugin breaks the user admin panel

Breaks on: 1.0.0-beta.10, 1.0.0-beta.9
Works on: 1.0.0-beta.7, 1.0.0-beta.8

### Steps to reproduce the behavior

1. Install plugin
2. Got to http://localhost:1337/admin/settings/users?pageSize=10&page=1&sort=firstname

### Screenshots

![image](https://github.com/pluginpal/strapi-webtools/assets/46526245/e623409a-6b32-4a6c-b2f6-d02a9cd39c36)

### System

- Node.js 18
- NPM version: 10.2.4
- YARN version: 1.22.19 (on Linux)
- BUN version: 1.1.1 (on Windows)
- Strapi version: 4.22.1
- Plugin version: 1.0.0-beta.10, 1.0.0-beta.9
- Database: sqlite
- Operating system: Windows 10/Linux

**Comment by ranaivomahaleo** [comment]
I breaks also on 1.0.0-beta.8

**Comment by boazpoolman** [comment]
This issue has been fixed with `v1.0.0-beta.11`.

If encounter any other problems feel free to open another issue.
