### ISSUE TITLE
Duplicated content maintain original url_alias id reference

### ISSUE THREAD

**Issue by colpomatteo** [pluginpal/strapi-webtools#138]
### Describe the bug

Hi, it's me again 😬. I have a problem when duplicating stuff.
Duplicated content (created with duplicate button) also duplicate the wt_url_alias relation table row without changing the id reference and without creating a new entry in the wt_url_alias table.

Thanks 🍻

### Steps to reproduce the behavior

1. Create an item of a collection type
2. Insert an url alias and unselect `Generate automatic URL alias`
3. Save
4. Duplicate the item with the duplicate button from the list view

### Expected behavior

A new item without url alias or with an automatic generated url alias is created.

### System

- Node.js version: v20.11.0
- NPM version: 10.2.4
- Strapi version: 4.20
- Plugin version: 1.0.0-beta.7
- Database: Postgres
- Operating system: Linux

**Comment by Alexnortung** [comment]
Hi @colpomatteo

This is a bug with strapi, I have opened [a pull request](https://github.com/strapi/strapi/pull/19740). please :+1: it and if you know anyone from Strapi, please have them review it :)

**Comment by boazpoolman** [comment]
This was fixed and released with version [1.0.0-beta.13](https://github.com/pluginpal/strapi-webtools/releases/tag/%40pluginpal%2Fwebtools-core%401.0.0-beta.13)
