### ISSUE TITLE
Remove from wt_url_alias table [DB] when removing item in content manager

### ISSUE THREAD

**Issue by MSACC** [pluginpal/strapi-webtools#140]
### Describe the bug

When removing items in content manager, the url alias link in wt_url_alias should also be removed.
### Steps to reproduce the behavior

1. Create page with url alias generated to it.
2. Remove page. URL alias stills remains in wt_url_alias table

### Expected behavior

URL alias is being removed from wt_url_alias table

**Comment by boazpoolman** [comment]
Context:

This issue happens when performing a bulk delete.
Singular deletes work as expected.

**Comment by boazpoolman** [comment]
This was fixed and released with version [1.0.0-beta.13](https://github.com/pluginpal/strapi-webtools/releases/tag/%40pluginpal%2Fwebtools-core%401.0.0-beta.13)
