### ISSUE TITLE
Usage with sitemap

### ISSUE THREAD

**Issue by Alexnortung** [pluginpal/strapi-webtools#20]
### Summary

It should be possible to use this plugin with the sitemap plugin to generate a sitemap.
This is also currently possible by setting allowed fields to also accept strings in the sitemap plugin. Then choosing to generate a sitemap from `UrlAliasPath` and using the `[url_path]` field.

However it should be possible to generate it from a specific content type such as a `page` content type. Currently there is only an accessible field for `url_path_id` which we cannot use to generate a sitemap.

### Suggested solution(s)

I am not sure how this should be implemented

### Related issue(s)/PR(s)

#9

**Comment by Alexnortung** [comment]
Thanks!

I guess this is also an issue with the ui navigation plugin, since it only gives the `url_path_id` and not `url_path`.
But this might be a separate issue.

**Comment by boazpoolman** [comment]
This has been released as a new package; Webtools Sitemap addon [`v1.0.0-beta.6`](https://github.com/pluginpal/strapi-webtools/releases/tag/%40pluginpal%2Fwebtools-addon-sitemap%401.0.0-beta.6)

If you're experiencing any issues with the new feature, please report a new issue.
