### ISSUE TITLE
Forbidden access with graphql

### ISSUE THREAD

**Issue by vsychov** [pluginpal/strapi-webtools#22]
## Bug report
Hello, thanks for great plugin.
I found issue very similar to #17, but with graphql

### Describe the bug
When I tried make query like this:
```graphql
query {
  urlAliasPaths(filters:{url_path:{eq:"/test"}}) {
    data {
      id
    }
  }
}
```

I'm getting error message:
```json
{
  "errors": [
    {
      "message": "Forbidden access",
      "extensions": {
        "error": {
          "name": "ForbiddenError",
          "message": "Forbidden access",
          "details": {}
        },
        "code": "FORBIDDEN"
      }
    }
  ],
  "data": {
    "urlAliasPaths": null
  }
}
```

It's happens because of missing permission `plugin::url-alias.path.find`, that I expect - should be generated by plugin, and inserted to strapi db.

After manually adding permission to database (via [config-sync plugin](https://market.strapi.io/plugins/strapi-plugin-config-sync), and allow it, everything works fine:
```json
{
  "action": "plugin::url-alias.path.find"
}
```

### Steps to reproduce the behavior

1. Execute query
2. Got error

### Expected behavior

Plugin should create permissions in strapi db ([like here](https://github.com/strapi/strapi/blob/main/packages/plugins/users-permissions/server/services/users-permissions.js#L180)) or expose it somehow to strapi.

### Screenshots

![5541ede8c57a](https://user-images.githubusercontent.com/2186303/193451956-ccfbe746-1f7e-47b9-93a4-7356a60619ec.png)

### System

- Node.js version: v14.20.0
- NPM version: 6.14.17
- Strapi version: v4.3.8
- Plugin version: 1.0.0-alpha.6
- Database: postgres
- Operating system: linux

**Comment by boazpoolman** [comment]
Hi @vsychov,

Agree with you on this one. The permissions of the public endpoints should be enabled by default through the plugin.

**Comment by boazpoolman** [comment]
This issue has been fixed in the latests `beta` release.
As of `beta`, the permissions for all the public endpoints will be granted by default.
