### ISSUE TITLE
Support for i18n/localization paths

### ISSUE THREAD

**Issue by urbgimtam** [pluginpal/strapi-webtools#30]
### Summary

Define different paths (or path section), according to the different locales

### Why is it needed?

People use Url paths for structuring the content. 

If we have a Page collection, and 2 languages EN and PT, and a structure like `/[locale]/page/[title]`, currently the plugin will generate examples like:

- /en/page/test-1
- /pt/page/teste-1
- /de/page/test-1

However, almost every time I'm trying to find a way to generate a localised part of the path, like:

- /en/page/test-1
- /pt/pagina/teste-1
- /de/seite/test-1

This would also benefit a lot when building a website, as:
- a single-source of truth where the URL paths are defined
- no routing re-creation of each page route on the front-end app (like a website)
- the url can be used to fetch the data immediately from the api, unambiguously.

### Suggested solution(s)

Coming from several years on the Drupal world, they had a PathAuto module, which works really similarly, but with a key difference - each pattern would be defined for each locale.
Instead of defining `/[locale]/page/[title]` for each collection, they would define it for each locale:

en: /en/page/[title]
pt: /pt/pagina/[title]
de: /de/seite/{title]

Thank you for the attention, and hoping this goes through.
```[tasklist]
### Tasks
```

**Comment by Alexnortung** [comment]
Hey @boazpoolman, we discussed transitioning to a monorepo, do you think we need an i18n package? Or could this go in the core?

**Comment by boazpoolman** [comment]
Hey @Alexnortung 
I think we should put this in core. Do you agree?

**Comment by boazpoolman** [comment]
Allright I'm sold. Let's make a seperate package out of it.
Let me spend some time on converting the repo to a monorepo and then we can get started on this.
I'll keep you posted @Alexnortung

**Comment by arastorhuiev** [comment]
Hi @Alexnortung, @boazpoolman, as I understand it, it is not yet possible to make a uid field of this type for one entry, but in different locales?

Example:
slugEnField: slug-1
slugGbField: slug-1

something like one uid field for one more locale?

**Comment by AdamSawkaGotoma** [comment]
@boazpoolman Hi friend, any update on this one?

**Comment by boazpoolman** [comment]
I haven't started work on this feature yet, though it's definitely on my radar!

I'm currently working on #14, so things are happening 😄

**Comment by boazpoolman** [comment]
This has been released with version [`1.0.0-beta.11`](https://github.com/pluginpal/strapi-webtools/releases/tag/%40pluginpal%2Fwebtools-core%401.0.0-beta.11)

If you're experiencing any issues with the new feature, please report a new issue.
