### ISSUE TITLE
Remove "Manual" alias for some content-types

### ISSUE THREAD

**Issue by Norbz** [pluginpal/strapi-webtools#42]
### Summary

Hello.
Now that we can disable URL-Alias for some content-type, I think we could benefit from having certains content-type alias not bein editable (ie, only generated).

### Why is it needed?

The base idea of using URL-Alias is to be able to have your frontend router agnotic about URI, giving more power to the adminitrator to create pages. It also mean using a single endpoint to retrieve all (or almost all)your content-type
Sometimes though, for specific pages, it could be useful to enforce a specific layout on router side, while maintaining the single endpoint. This would also give the strapi administrator the information about the URL on frontend.

Ex: Having a list of tag with generated URL only (/tags/[slug]) would correspond on frontend side to a specific component (/tags/[slug].vue using nuxt 3 for instance) which would do some more complex behavior than a single page, displaying several articles related to the tag.

### Suggested solution(s)

Adding another checkbox on content-type options to prevent Alias edition.

### Disclosure
I used to maintain the "custom-link" plugin available on strapi marketplace but I don't have enough time right now to work on it right now. I guess I should focus on trying to improve this one instead.

**Comment by boazpoolman** [comment]
I guess this would be most easily solved by using admin permissions to revoke the right of editing the URL alias.

Then you could just revoke those rights for the editor role and we've achieved what you describe here.

**Comment by TMSchipper** [comment]
Hi @Norbz, I reviewed your request, and I can confirm that this can be achieved using the plugin settings. If you leave the checkbox blank the user will not have the url alias sidebar.

<img width="902" alt="Screenshot 2024-05-20 at 18 33 39" src="https://github.com/pluginpal/strapi-webtools/assets/55846250/3211b430-b71c-4dff-9dc8-4d95b1da8dac">

If you can confirm that this resolves your issue, I'll close this issue.


Thank you for your time.

**Comment by Norbz** [comment]
Hi @TMSchipper 

This is perfect, and a great use for some use cases. Thank you for the update =)
