### ISSUE TITLE
Clean up old paths

### ISSUE THREAD

**Issue by Alexnortung** [pluginpal/strapi-webtools#51]
### Describe the bug

In some cases there might exist paths with no valid entry, which means the url path is in the database, but there is no associated entry.

This can happen if a content type has enabled url alias and have some entries with paths and then it gets disabled.

### Steps to reproduce the behavior

1. Create new content type with url alias enabled
2. Create an entry for that content type with a url path of `/home`
3. disable url alias from the content type
4. create a new entry of a content type that has enabled url alias and give it a url path of `/home`
5. observe that the url path will be saved as `/home-0`

### Expected behavior

I think I would expect url alias to clean the old paths up by itself, although this might be a large task with the current setup if done during bootstrap and the instance has a lot of entries.

I think a way to fix this is to provide the user with a button which would clean up the old paths. However this doesn't really seem satisfiable either.

**Comment by Alexnortung** [comment]
Maybe this can be solved very simply by just using the query engine during bootstrap. So something like:

```
const enabledContentTypes = getEnabledContentTypes
strapi.db.query("plugin::url-alias.path").deleteMany({
  where: {
    contenttype: {
      $notIn: enabledContentTypes,
    },
  },
});
```

**Comment by boazpoolman** [comment]
I can get behind this solution.
Does Strapi bootstrap when a content type schema changes? I believe it does.

**Comment by Alexnortung** [comment]
Yes, it bootstraps every time strapi starts. So that includes when the schema changes :)

Den 14. september 2023 07.55.13 CEST, Boaz Poolman ***@***.***> skrev:

**Comment by boazpoolman** [comment]
Sweet. Then let's do it.

Though just for the record, #14 would still have to be implemented for when URL alias would be enabled again.
