### ISSUE TITLE
Automatic path generation should be disabled when no pattern is found

### ISSUE THREAD

**Issue by Norbz** [pluginpal/strapi-webtools#54]
### Describe the bug

When adding a new entry for a content-type you forgot to add a pattern for, the plugin ends-up adding a strange `-0` path. This path then stays in the database when either adding a pattern or adding a custom "manual" path.

### Steps to reproduce the behavior

1. Add a new content-type "Foo" with url-alias activated
2. Go to add a new "Foo" entry
3. Save
4. path is now `-0` and associated with no entry

### Expected behavior

Either deactivate the automatic generation if no pattern is found, or rely on a generic pattern such as `/[content-type]/[id]`
(ie: /foo/1)

- Node.js version: 18.17.0
- NPM version: 9.x
- Strapi version: 4.12.7
- Plugin version: beta.10
- Database: mysql
- Operating system: ubuntu / MacOS

**Comment by boazpoolman** [comment]
This issue was fixed with [this PR](https://github.com/pluginpal/strapi-webtools/pull/118) and released with [version 1.0.0-beta.6](https://github.com/pluginpal/strapi-webtools/releases/tag/%40pluginpal%2Fwebtools-core%401.0.0-beta.6).
