### ISSUE TITLE
Add "Edit path" as an admin authorisation so we can remove path edition for some administrator role

### ISSUE THREAD

**Issue by Norbz** [pluginpal/strapi-webtools#55]
### Summary

I'd love to be able to remove the ability to edit the path for some administrators the same way I can prevent them to edit patterns.
In the case of an entry creation, the plugin would tehn remain on automatic generation

### Why is it needed?

You might want to have some pages that you need the path to stay intact, like the home page, and this could prevent some administrators to break the frontend

### Suggested solution(s)

A new option here would be perfect :)
![Capture d’écran 2023-09-13 à 17 36 11](https://github.com/strapi-community/strapi-plugin-url-alias/assets/6388929/2abace0a-9e28-42c7-84b3-b6508011714d)

**Comment by boazpoolman** [comment]
This issue was fixed with [this PR](https://github.com/pluginpal/strapi-webtools/pull/117) and released with [version 1.0.0-beta.6](https://github.com/pluginpal/strapi-webtools/releases/tag/%40pluginpal%2Fwebtools-core%401.0.0-beta.6).
