### ISSUE TITLE
Strapi 4.15.5. ./dist/core-api/controller/transform' is not defined by "exports"

### ISSUE THREAD

**Issue by portedison** [pluginpal/strapi-webtools#69]
New Strapi project (4.15.5)
Then install plugin
yarn build

Error: Could not load js config file
/path/test-plugin/node_modules/@strapi-community/strapi-plugin-url-alias/strapi-server.js: Package subpath 
'./dist/core-api/controller/transform' is not defined by "exports" in
/path/test-plugin/node_modules/@strapi/strapi/package.json

I'm a bit fresh with this but is it the way that it's being imported? I've copied this into /plugins folder and changed to -

// import { transformResponse } from '@strapi/strapi/dist/core-api/controller/transform';
const { transformResponse } = require('@strapi/strapi');

It builds and I can run `yarn develop` though I haven't tested the api path yet.

**Comment by portedison** [comment]
I suspect it's just not up to date with the latest version of Strapi? I also had to get all of the latest dependencies, which seemed to go pretty seamlessly.

And another thing, it seems this was preventing my Page / Article items from displaying  - 
if (!isContentTypeEnabled(uid)) {
      return;
}
Commenting this out adds them all in. I'm not sure if there is a new bug, otherwise there's a step not documented in 'enabling' types. I've yet to debug this bit.

**Comment by portedison** [comment]
I can't seem to find any examples that refer to ./dist/... like you do here - 
https://github.com/strapi-community/strapi-plugin-url-alias/blob/master/strapi-admin.js

That seems to cause some issues in development.?

**Comment by boazpoolman** [comment]
Hi @portedison,

Thanks for reporting this issue.
Let me start by saying the plugin is in the middle of a big rewrite and hasn't gotten any alpha releases lately.

The issue you're describing about the transform response is something I'll take a look at.

About the URL alias not showing up. This is intended. Starting alpha.11 URL alias will be disabled by default. To migrate please see the MIGRATION.md doc.

**Comment by boazpoolman** [comment]
This issue has been resolved in the latests `beta` release 🎉
