### ISSUE TITLE
Path field in retrieved data

### ISSUE THREAD

**Issue by colpomatteo** [pluginpal/strapi-webtools#92]
### Summary

I liked the "url_path" field in the old url-alias plugin, it is useful in some cases.

### Why is it needed?

You may need to have the path of the content you're retrieving (for links, reference...)

**Comment by boazpoolman** [comment]
It’s still there. Though it’s now called `url_alias` and it’s a relation field. Meaning you’ll have to populate it to get it’s data.

**Comment by boazpoolman** [comment]
Might have to write some documentation about this

**Comment by colpomatteo** [comment]
Thaks for your quick response! Great news, thank you.
Also, i will migrate from old url_alias plugin to new strapi-webtools, is there an easy way to preserve data? I saw the migration script which renames the tables but i didn't saw the content<->alias relation table creation (in the url-alias plugin the relation is just a field in the content type table). Am I missing something?

**Comment by boazpoolman** [comment]
There are also some migration scripts in place to accomodate the data movement. See https://github.com/pluginpal/strapi-webtools/tree/master/packages/core/server/admin-api/migrations

As long as you follow the migration guide you should be good

**Comment by colpomatteo** [comment]
Great, thank you! 🍻

**Comment by boazpoolman** [comment]
Please let me know how the migration process goes. I haven’t had much feedback on it apart from the other maintainers of this plugin.

**Comment by colpomatteo** [comment]
Sure, it’s not gonna be soon but I will (it is planned tho).

**Comment by colpomatteo** [comment]
Hey man, so I started the upgrade and I had some problems 😅.

1. When the migration script rename the 'url_paths' table it doesn't rename the column 'path' to 'url_path' consequentially you loose all the informations.
2. I went crazy because in the migration guide it isn't mentioned that you need to add the following code to every schema pluginOptions otherwise the migration goes well but when the plugin core is loaded it'll wipe all the data.
```
"webtools": {
      "enabled": true
}
```
4. On the link tables created by the script the column name is different from singularName (on table creation knex automatically fixes the name replacing '-' with '_' but not in the insert), so you lose data (without errors). 

At the end of this i would suggest to use transactions so you can rollback if something goes wrong and you don't lose data.
Done all the mods the procedure went well 🍻.

**Comment by Alexnortung** [comment]
I think it does say to enable webtools (or url alias) in the [alpha migration](https://github.com/pluginpal/strapi-webtools/blob/master/MIGRATION.md#from-alpha9-or-10-to-alpha11)

I think the knex migration is a transaction, so if anything goes wrong during the migration, it is rolled back. But strapi will delete tables not used, so you are right, if the tables are named something different strapi will delete it.

I would say I was unaware that the singular names included `-` maybe we should make that more clear in the migration guide?

**Comment by colpomatteo** [comment]
🤦‍♂️ I didn't look at the alpha migration (it says url alias but anyway I should have read to the end before starting).
The first attempt I made didn't go well but it also didn't rolled back, my strapi is inside a docker container tho so maybe the container crashed before it had time to roll back.
I think when you have types with spaces in the display name, strapi converts it to "-" in singular names and "_" in collection names but regardless of this i think kenx does some manipulation to column names when it alters tables so maybe "-"/"_" conversion is not the only thing it does.

**Comment by Alexnortung** [comment]
Setting the pluginOptions of `url_alias` is enough since it will automatically be changed to `webtools` once you launch strapi. :)

If you change the singular name in the migration file to snake case is that enough? Or do you have other issues?

**Comment by colpomatteo** [comment]
I didn't had any other issues, apart this

> When the migration script rename the 'url_paths' table it doesn't rename the column 'path' to 'url_path' consequentially you loose all the informations.

**Comment by Alexnortung** [comment]
Has the `url_path` field previously been named `path`?

**Comment by colpomatteo** [comment]
In my table the column was named `path` 🤷‍♂️

**Comment by Alexnortung** [comment]
Ahh looks like it happened a while ago in [this commit](https://github.com/pluginpal/strapi-webtools/commit/b14eb26f76b53a3a9ad91f050b04266224fc244d). I am not sure if there has ever been added any migration for this, but I think it is worth to add to the migration script.

**Comment by Alexnortung** [comment]
@colpomatteo, I have opened a PR, do you think this covers the things you had trouble with?

**Comment by colpomatteo** [comment]
Yes

**Comment by colpomatteo** [comment]
I read your `NOTE`, just to be precise: singularName needs to be snakeCase not **kebabCase** (instead of CamelCase, i didn't tried camelCase names)

**Comment by Alexnortung** [comment]
Thanks, yes it should be kebab-case, I have changed it now :)
