### ISSUE TITLE
locale in patterns is no longer being resolved

### ISSUE THREAD

**Issue by Alexnortung** [pluginpal/strapi-webtools#96]
### Describe the bug

Having `[locale]` in a pattern is no longer getting resolved. If I have a pattern `/[locale]/[title]` and saving an entry with title `x`, then the generated url alias will be `/[locale]/x`

### Steps to reproduce the behavior

1. Create a pattern with `[locale}` in it
2. Create an entry with it
3. See that the locale has not been resolved

### Expected behavior

I expected that the locale would be resolved as, so if the entry has a locale of `en` I would expect the url apth to be `/en/x`

**Comment by boazpoolman** [comment]
Thanks for reporting the bug @Alexnortung!

I'll take a look at this tonight.

**Comment by boazpoolman** [comment]
Issue confirmed

**Comment by boazpoolman** [comment]
@Alexnortung I've opened a PR which should fix this issue.
Could you check that out? #98

**Comment by boazpoolman** [comment]
Fix was released with [core@1.0.0-beta.5](https://github.com/pluginpal/strapi-webtools/releases/tag/%40pluginpal%2Fwebtools-core%401.0.0-beta.5)

**Comment by Alexnortung** [comment]
Thanks @boazpoolman
